openapi: 3.0.1
info:
  description: This is the REST API for the in-situ pipeline.
  title: In-Situ Pipeline REST API
  version: 1.0.0
servers:
- url: http://localhost/v1
paths:
  /arbor/attributes:
    get:
      operationId: arbor_get_attributes
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                - Voltage
                - Current
                items:
                  type: string
                type: array
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                example: Error message
                type: string
          description: Operation failed.
      summary: Retrieves a list of all attributes.
      tags:
      - arbor
      x-swagger-router-controller: access_node.controllers.arbor_controller
      x-openapi-router-controller: access_node.controllers.arbor_controller
  /arbor/cell_ids:
    get:
      operationId: arbor_get_cell_ids
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                - 1
                - 2
                items:
                  format: uint64
                  type: integer
                type: array
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                example: Error message
                type: string
          description: Operation failed.
      summary: Retrieves a list of all cell ids.
      tags:
      - arbor
      x-swagger-router-controller: access_node.controllers.arbor_controller
      x-openapi-router-controller: access_node.controllers.arbor_controller
  /arbor/cell_properties:
    get:
      operationId: arbor_get_cell_properties
      parameters:
      - description: A list of cell IDs queried for properties.
        explode: false
        in: query
        name: cell_ids
        required: false
        schema:
          items:
            format: uint64
            type: integer
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ArborCellProperties'
                type: array
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                example: Error message
                type: string
          description: Operation failed.
      summary: Retrieves the properties of the specified cells.
      tags:
      - arbor
      x-swagger-router-controller: access_node.controllers.arbor_controller
      x-openapi-router-controller: access_node.controllers.arbor_controller
  /arbor/measurements:
    get:
      operationId: arbor_get_measurements
      parameters:
      - description: The attribute to query
        explode: true
        in: query
        name: attribute
        required: true
        schema:
          type: string
        style: form
      - description: A list of probes ids queried for data.
        explode: false
        in: query
        name: probe_ids
        required: false
        schema:
          items:
            format: uint64
            type: integer
          type: array
        style: form
      - description: The start time (including) to be queried.
        explode: true
        in: query
        name: from
        required: false
        schema:
          format: double
          type: number
        style: form
      - description: The end time (excluding) to be queried.
        explode: true
        in: query
        name: to
        required: false
        schema:
          format: double
          type: number
        style: form
      - description: The offset into the result.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          format: uint64
          type: integer
        style: form
      - description: The maximum number of entries to be returned.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: uint64
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArborMeasurement'
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                example: Error message
                type: string
          description: Operation failed.
      summary: Retrieves the measurements for given probes (optional).
      tags:
      - arbor
      x-swagger-router-controller: access_node.controllers.arbor_controller
      x-openapi-router-controller: access_node.controllers.arbor_controller
  /arbor/probes:
    get:
      operationId: arbor_get_probes
      parameters:
      - description: The attribute measured for which existing probes will be returned.
        explode: true
        in: query
        name: attribute
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Probe'
                type: array
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                example: Error message
                type: string
          description: Operation failed.
      summary: Retrieves a list of all probes for a given attribute (optional).
      tags:
      - arbor
      x-swagger-router-controller: access_node.controllers.arbor_controller
      x-openapi-router-controller: access_node.controllers.arbor_controller
  /arbor/simulation_time_info:
    get:
      operationId: arbor_get_simulation_time_info
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulationTimeInfo'
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                example: Error message
                type: string
          description: Operation failed.
      summary: Retrieves simulation time information(begin, current, end).
      tags:
      - arbor
      x-swagger-router-controller: access_node.controllers.arbor_controller
      x-openapi-router-controller: access_node.controllers.arbor_controller
  /arbor/spikes:
    get:
      operationId: arbor_get_spikes
      parameters:
      - description: The start time (including) to be queried.
        explode: true
        in: query
        name: from
        required: false
        schema:
          format: double
          type: number
        style: form
      - description: The end time (excluding) to be queried.
        explode: true
        in: query
        name: to
        required: false
        schema:
          format: double
          type: number
        style: form
      - description: A list of cell ids queried for spike data.
        explode: false
        in: query
        name: cell_ids
        required: false
        schema:
          items:
            format: uint64
            type: integer
          type: array
        style: form
      - description: A list of segment ids queried for spike data.
        explode: false
        in: query
        name: segment_ids
        required: false
        schema:
          items:
            format: uint64
            type: integer
          type: array
        style: form
      - description: The offset into the result.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          format: uint64
          type: integer
        style: form
      - description: The maximum number of entries to be result.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: uint64
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spikes'
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                example: Error message
                type: string
          description: Operation failed.
      summary: Retrieves the spikes for the given simulation times (optional), cell
        and segment (optional).
      tags:
      - arbor
      x-swagger-router-controller: access_node.controllers.arbor_controller
      x-openapi-router-controller: access_node.controllers.arbor_controller
  /nest/multimeters:
    get:
      operationId: nest_get_multimeters
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/MultimeterInfo'
                type: array
          description: Operation successful.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Retreives the available multimeters and their properties.
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/multimeters/{multimeterId}:
    get:
      operationId: nest_get_multimeter_by_id
      parameters:
      - description: The identifier of the multimeter.
        explode: false
        in: path
        name: multimeterId
        required: true
        schema:
          format: uint64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MultimeterInfo'
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to invalid request.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Retreives the available multimeters and their properties.
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/multimeters/{multimeterId}/attributes/{attributeName}:
    get:
      operationId: nest_get_multimeter_measurements
      parameters:
      - description: The multimeter to query
        explode: false
        in: path
        name: multimeterId
        required: true
        schema:
          format: uint64
          type: integer
        style: simple
      - description: The attribute to query (e.g., 'V_m' for the membrane potential)
        explode: false
        in: path
        name: attributeName
        required: true
        schema:
          type: string
        style: simple
      - description: The start time (including) to be queried.
        explode: true
        in: query
        name: fromTime
        required: false
        schema:
          format: double
          type: number
        style: form
      - description: The end time (excluding) to be queried.
        explode: true
        in: query
        name: toTime
        required: false
        schema:
          format: double
          type: number
        style: form
      - description: A list of neuron IDs queried for attribute data.
        explode: false
        in: query
        name: neuronIds
        required: false
        schema:
          items:
            format: uint64
            type: integer
          type: array
        style: form
      - description: The offset into the result.
        explode: true
        in: query
        name: skip
        required: false
        schema:
          format: uint64
          type: integer
        style: form
      - description: The maximum number of entries to be returned.
        explode: true
        in: query
        name: top
        required: false
        schema:
          format: uint64
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MultimeterMeasurement'
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to invalid request.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Retrieves the measurements for a multimeter, attribute and neuron IDs
        (optional).
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/neurons:
    get:
      operationId: nest_get_neurons
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/NestNeuronProperties'
                type: array
          description: Operation successful.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Retrieves the properties of the specified neurons.
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/neurons/ids:
    get:
      operationId: nest_get_neuron_ids
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                - 1
                - 2
                - 3
                - 15
                items:
                  format: uint64
                  type: integer
                type: array
          description: Operation successful.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed.
      summary: Retrieves a list of all neuron IDs accessable via the pipeline.
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/neurons/{neuronId}:
    get:
      operationId: nest_get_neuron_by_id
      parameters:
      - description: The ID of the queried neuron.
        explode: false
        in: path
        name: neuronId
        required: true
        schema:
          format: uint64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NestNeuronProperties'
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to invalid request.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Retrieves the properties of the specified neuron.
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/populations:
    get:
      operationId: nest_get_populations
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                - 1
                - 2
                - 3
                items:
                  format: uint64
                  type: integer
                type: array
          description: Operation successful.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Retrieves a list of all accessable population IDs.
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/populations/${populationId}/neurons/ids:
    get:
      operationId: nest_get_neuron_ids_by_population
      parameters:
      - description: The identifier of the population
        explode: false
        in: path
        name: populationId
        required: true
        schema:
          format: uint64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                - 1
                - 2
                items:
                  format: uint64
                  type: integer
                type: array
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to invalid request.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Retrieves the list of all neuron ids within the population.
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/populations/{populationId}/neurons:
    get:
      operationId: nest_get_neurons_by_population
      parameters:
      - description: The population ID to query the neurons for.
        explode: false
        in: path
        name: populationId
        required: true
        schema:
          items:
            format: uint64
            type: integer
          type: array
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/NestNeuronProperties'
                type: array
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to invalid request.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Retrieves the neurons that belong to the specified population.
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/populations/{populationId}/spikes:
    get:
      operationId: nest_get_spikes_by_population
      parameters:
      - description: The identifier of the population.
        explode: false
        in: path
        name: populationId
        required: true
        schema:
          format: uint64
          type: integer
        style: simple
      - description: The start time (including) to be queried.
        explode: true
        in: query
        name: fromTime
        required: false
        schema:
          format: double
          type: number
        style: form
      - description: The end time (excluding) to be queried.
        explode: true
        in: query
        name: toTime
        required: false
        schema:
          format: double
          type: number
        style: form
      - description: The offset into the result.
        explode: true
        in: query
        name: skip
        required: false
        schema:
          format: uint64
          type: integer
        style: form
      - description: The maximum numbers of entries to be returned.
        explode: true
        in: query
        name: top
        required: false
        schema:
          format: uint64
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spikes'
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to invalid request.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Retrieves the spikes for the given simulation steps (optional) and
        population. This request merges the spikes recorded by all spike detectors
        and removes duplicates.
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/simulationTimeInfo:
    get:
      operationId: nest_get_simulation_time_info
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulationTimeInfo'
          description: Operation successful.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed.
      summary: Retrieves simulation time information (stepSize, begin, current, end).
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/spikedetectors/:
    get:
      operationId: nest_get_spikedetectors
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpikedetectorInfo'
          description: Operation successful.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Queries all spike detectors accessable to the pipeline.
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/spikedetectors/{spikedetectorId}/spikes:
    get:
      operationId: nest_get_spikes_by_spikedetector
      parameters:
      - description: The ID of the spike detector to query.
        explode: false
        in: path
        name: spikedetectorId
        required: true
        schema:
          format: uint64
          type: integer
        style: simple
      - description: The start time in milliseconds (including) to be queried.
        explode: true
        in: query
        name: fromTime
        required: false
        schema:
          format: double
          type: number
        style: form
      - description: The end time in milliseconds (excluding) to be queried.
        explode: true
        in: query
        name: toTime
        required: false
        schema:
          format: double
          type: number
        style: form
      - description: A list of neuron IDs queried for spike data.
        explode: false
        in: query
        name: neuronIds
        required: false
        schema:
          items:
            format: uint64
            type: integer
          type: array
        style: form
      - description: The offset into the result.
        explode: true
        in: query
        name: skip
        required: false
        schema:
          format: uint64
          type: integer
        style: form
      - description: The maximum number of entries to be returned.
        explode: true
        in: query
        name: top
        required: false
        schema:
          format: uint64
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spikes'
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to invalid request.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Retrieves the spikes for the given time range (optional) and neuron
        IDs (optional) from one spike detector. If no time range or neuron list is
        specified, it will return the spikes for whole time or all neurons respectively.
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /nest/spikes:
    get:
      operationId: nest_get_spikes
      parameters:
      - description: The start time in milliseconds (including) to be queried.
        explode: true
        in: query
        name: fromTime
        required: false
        schema:
          format: double
          type: number
        style: form
      - description: The end time in milliseconds (excluding) to be queried.
        explode: true
        in: query
        name: toTime
        required: false
        schema:
          format: double
          type: number
        style: form
      - description: A list of neuron IDs queried for spike data.
        explode: false
        in: query
        name: neuronIds
        required: false
        schema:
          items:
            format: uint64
            type: integer
          type: array
        style: form
      - description: The offset into the result.
        explode: true
        in: query
        name: skip
        required: false
        schema:
          format: uint64
          type: integer
        style: form
      - description: The maximum number of entries to be returned.
        explode: true
        in: query
        name: top
        required: false
        schema:
          format: uint64
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spikes'
          description: Operation successful.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to invalid request.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Retrieves the spikes for the given time range (optional) and neuron
        IDs (optional). If no time range or neuron list is specified, it will return
        the spikes for whole time or all neurons respectively. This request merges
        the spikes recorded by all spike detectors and removes duplicates.
      tags:
      - nest
      x-swagger-router-controller: access_node.controllers.nest_controller
      x-openapi-router-controller: access_node.controllers.nest_controller
  /version:
    get:
      operationId: get_version
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
          description: Operation successful.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Operation failed due to server error.
      summary: Returns the deployed insite and API versions.
      x-swagger-router-controller: access_node.controllers.version_controller
      x-openapi-router-controller: access_node.controllers.default_controller
components:
  schemas:
    Version:
      example:
        api:
          v1: "1.3"
          v2: "2.1"
          v3: "3.5"
        insite: "4.6"
      properties:
        api:
          type: string
        insite:
          type: string
      required:
      - api
      - insite
      type: object
    ErrorResponse:
      properties:
        error:
          $ref: '#/components/schemas/Error'
      required:
      - error
      type: object
    Error:
      properties:
        code:
          description: 'One of the error codes defined here: [...]'
          type: string
        message:
          description: A human-readable representation of the error.
          type: string
        innererror:
          $ref: '#/components/schemas/InnerError'
      required:
      - code
      - message
      type: object
    InnerError:
      properties:
        code:
          description: 'One of the error codes defined here: [...]'
          type: string
        innererror:
          $ref: '#/components/schemas/InnerError'
      required:
      - code
      type: object
    Spikes:
      example:
        simulationTimes:
        - 0.8
        - 0.9
        neuronIds:
        - 1
        - 2
      properties:
        simulationTimes:
          description: This array is always sorted.
          items:
            format: double
            type: number
          type: array
        neuronIds:
          items:
            format: uint64
            type: integer
          type: array
      type: object
    MultimeterMeasurement:
      example:
        simulationTimes:
        - 0.1
        - 0.2
        neuronIds:
        - 1
        - 2
        - 3
        values:
        - 0.123
        - 0.123
        - 0.123
        - 0.123
        - 0.123
        - 0.123
      properties:
        simulationTimes:
          description: This array is always sorted.
          items:
            format: double
            type: number
          type: array
        neuronIds:
          items:
            format: uint64
            type: integer
          type: array
        values:
          description: This array contains the measured values for each neuron ID
            and time to get the value for neuron ID n at time t you have to use the
            index n * length(simulationTimes) + t
          items:
            type: number
          type: array
      type: object
    ArborMeasurement:
      example:
        simulation_times:
        - 0.1
        - 0.2
        gids:
        - 1
        - 2
        - 3
        values:
        - 0.123
        - 0.123
        - 0.123
        - 0.123
        - 0.123
        - 0.123
      properties:
        simulation_times:
          description: This array is always sorted.
          items:
            format: double
            type: number
          type: array
        gids:
          items:
            format: uint64
            type: integer
          type: array
        values:
          description: This array contains the measured values for each gid and time
            to get the value for gid n at time t you have to use the index n * length(simulation_times)
            + t
          items:
            type: number
          type: array
      type: object
    Probe:
      example:
        id: 1
        cell_id: 2
        segment_id: 1
        position: 0.4
      properties:
        id:
          format: uint64
          type: integer
        cell_id:
          format: uint64
          type: integer
        segment_id:
          format: uint64
          type: integer
        position:
          format: double
          type: number
      type: object
    ArborCellProperties:
      example:
        population: pop1
        position:
        - 0.1
        - 0.1
        - 0.1
      properties:
        neuron_id:
          format: uint64
          type: integer
        properties:
          properties: {}
          type: object
      type: object
    NestNeuronProperties:
      example:
        neuronId: 1
        properties:
          population: 2
          position:
          - 0.1
          - 0.1
          - 0.1
      properties:
        neuronId:
          format: uint64
          type: integer
        properties:
          properties: {}
          type: object
      type: object
    SimulationTimeInfo:
      example:
        stepSize: 0.1
        current: 2.1
        begin: 0.1
        end: 4.5
      properties:
        stepSize:
          format: double
          type: number
        begin:
          format: double
          type: number
        end:
          format: double
          type: number
        current:
          format: double
          type: number
      type: object
    MultimeterInfo:
      example:
        id: 0
        attributes:
        - V_m
        neuronIds:
        - 0
        - 1
        - 3
        - 5
      properties:
        id:
          format: uint64
          type: integer
        attributes:
          items:
            type: string
          type: array
        neuronIds:
          items:
            format: uint64
            type: integer
          type: array
      type: object
    SpikedetectorInfo:
      example:
        id: 0
        neuronIds:
        - 0
        - 1
        - 3
        - 5
      properties:
        id:
          format: uint64
          type: integer
        neuronIds:
          items:
            format: uint64
            type: integer
          type: array
      type: object
